### ISSUE TITLE
clicking an image in the file explorer raises an error

### ISSUE THREAD

**Issue by tmaybe** [chimecms/chime#138]
A 'no front-matter' error as raised in jekyll_functions.py / load_jekyll_doc()

**Comment by tmaybe** [comment]
probably related to #119

**Comment by migurski** [comment]
This issue is still current.

```
Traceback (most recent call last):
  File "/Users/migurski/Sites/Bizarro-CMS/chime/view_functions.py", line 452, in decorated_function
    return route_function(*args, **kwargs)
  File "/Users/migurski/Sites/Bizarro-CMS/chime/view_functions.py", line 505, in decorated_function
    return route_function(*args, **kwargs)
  File "/Users/migurski/Sites/Bizarro-CMS/chime/view_functions.py", line 584, in decorated_function
    return route_function(*args, **kwargs)
  File "/Users/migurski/Sites/Bizarro-CMS/chime/views.py", line 305, in branch_edit
    return render_edit_view(repo, branch_name, path, open(full_path, 'r'))
  File "/Users/migurski/Sites/Bizarro-CMS/chime/view_functions.py", line 1108, in render_edit_view
    front, body = load_jekyll_doc(file)
  File "/Users/migurski/Sites/Bizarro-CMS/chime/jekyll_functions.py", line 102, in load_jekyll_doc
    return {}, file.read().decode('utf8')
  File "/Users/migurski/Sites/Bizarro-CMS/venv-bizarro/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xff in position 0: invalid start byte
```
