### ISSUE TITLE
trying to delete some activities errors

### ISSUE THREAD

**Issue by tmaybe** [chimecms/chime#293]
Like so:

```
2015-06-26 21:42:42,426 - chime.view_functions - ERROR - 'git merge-base master a49ede9' returned exit status 128: fatal: Not a valid object name a49ede9
Traceback (most recent call last):
  File "/home/ubuntu/chime/chime/view_functions.py", line 432, in decorated_function
    return route_function(*args, **kwargs)
  File "/home/ubuntu/chime/chime/view_functions.py", line 464, in decorated_function
    return route_function(*args, **kwargs)
  File "/home/ubuntu/chime/chime/view_functions.py", line 520, in decorated_function
    response = route_function(*args, **kwargs)
  File "/home/ubuntu/chime/chime/views.py", line 263, in update_activity
    action, action_authorized = update_activity_review_status(branch_name=safe_branch, comment_text=u'', action_list=action_list)
  File "/home/ubuntu/chime/chime/views.py", line 664, in update_activity_review_status
    working_branch_name=branch_name, actor_email=session.get('email', None)
  File "/home/ubuntu/chime/chime/repo_functions.py", line 627, in get_review_state_and_authorized
    state, author_email = get_review_state_and_author_email(repo, default_branch_name, working_branch_name)
  File "/home/ubuntu/chime/chime/repo_functions.py", line 650, in get_review_state_and_author_email
    base_commit_hexsha = repo.git.merge_base(default_branch_name, working_branch_name)
  File "/usr/local/lib/python2.7/dist-packages/git/cmd.py", line 227, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/git/cmd.py", line 456, in _call_process
    return self.execute(call, **_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/git/cmd.py", line 377, in execute
    raise GitCommandError(command, status, stderr_value)
GitCommandError: 'git merge-base master a49ede9' returned exit status 128: fatal: Not a valid object name a49ede9

Request info:
<Request 'http://chime.chimecms.org/update' [POST]>
```

**Comment by tmaybe** [comment]
This is happening when you try to delete an activity/branch created by someone else that you haven't pulled to your local repo yet.
