### ISSUE TITLE
Resolve confusion between branches and tags

### ISSUE THREAD

**Issue by migurski** [chimecms/chime#460]
Possibly related to #433, this error from yesterday suggests that both branch and tag were in place at the same time:

```
2015-08-13 13:38:18,805 - chime.view_functions - ERROR - 'git push origin pvpwltpxw' returned exit status 1: error: src refspec pvpwltpxw matches more than one.
error: failed to push some refs to '/var/opt/chime/data/default/repo'
Traceback (most recent call last):
 File "/opt/chime/webapp/chime/view_functions.py", line 452, in decorated_function
   return route_function(*args, **kwargs)
 File "/opt/chime/webapp/chime/view_functions.py", line 505, in decorated_function
   return route_function(*args, **kwargs)
 File "/opt/chime/webapp/chime/view_functions.py", line 584, in decorated_function
   return route_function(*args, **kwargs)
 File "/opt/chime/webapp/chime/views.py", line 465, in branch_edit_file
   repo_functions.save_working_file(clone=repo, path=file_path, message=commit_message, base_sha=commit.hexsha, default_branch_name=master_name)
 File "/opt/chime/webapp/chime/repo_functions.py", line 530, in save_working_file
   clone.git.push('origin', active_branch_name)
 File "/usr/local/lib/python2.7/dist-packages/git/cmd.py", line 227, in <lambda>
   return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
 File "/usr/local/lib/python2.7/dist-packages/git/cmd.py", line 456, in _call_process
   return self.execute(call, **_kwargs)
 File "/usr/local/lib/python2.7/dist-packages/git/cmd.py", line 377, in execute
   raise GitCommandError(command, status, stderr_value)
GitCommandError: 'git push origin pvpwltpxw' returned exit status 1: error: src refspec pvpwltpxw matches more than one.
error: failed to push some refs to '/var/opt/chime/data/default/repo'

Request info:
<Request 'http://edit.orlando-fl.chimecms.org/tree/pvpwltpxw/edit/categories/licensing-permits/residential/' [POST]>
```

**Comment by tmaybe** [comment]
Can we reproduce this error, or have we seen it in the last couple of weeks? We've done a lot of work around this area and it may've been fixed.

**Comment by wpietri** [comment]
Searching for "matches more than one", I believe this is the only occurrence. Let's assume things are better; we can reopen if not.
