### ISSUE TITLE
IterableList origin attribute

### ISSUE THREAD

**Issue by migurski** [chimecms/chime#521]
This is weird, since it happens in a function that gets called all the damn time:

```
2015-09-01 15:33:30,548 - chime.view_functions - ERROR - 'IterableList' object has no attribute 'origin'
Traceback (most recent call last):
  File "/opt/chime/webapp/chime/view_functions.py", line 482, in decorated_function
    return route_function(*args, **kwargs)
  File "/opt/chime/webapp/chime/view_functions.py", line 539, in decorated_function
    return route_function(*args, **kwargs)
  File "/opt/chime/webapp/chime/view_functions.py", line 666, in decorated_function
    return route_function(*args, **kwargs)
  File "/opt/chime/webapp/chime/views.py", line 253, in branch_view
    repo = get_repo(flask_app=current_app)
  File "/opt/chime/webapp/chime/view_functions.py", line 131, in get_repo
    user_repo.remotes.origin.fetch()
  File "/usr/local/lib/python2.7/dist-packages/git/util.py", line 669, in __getattr__
    return list.__getattribute__(self, attr)
AttributeError: 'IterableList' object has no attribute 'origin'
```

**Comment by tmaybe** [comment]
I bet it's a GitPython upgrade issue...looking into it now
